import type { Metadata } from 'next'
import { Archivo } from 'next/font/google'
import './globals.css'
import db from '@/lib/supabase/db'

const font = Archivo({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  console.log(db)
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
